package fr.flst.mmargr.model;

//default package
//Generated 11 mai 2014 14:24:29 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.Range;


/**
* Article generated by hbm2java
*/
@Entity
@Table(name = "article", catalog = "java")
public class Article implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3922304456939904565L;
	
	private Integer id;
	private Enseigne enseigne;
	private String referenceArticle;
	private String descriptionCourte;
	private String modele;
	private int quantite;
	private String descriptionLongue;
	private double prix;
	private String image;
	private boolean superClient = false;
	private boolean actif = true;

	public Article() {
		
	}

	public Article(Enseigne enseigne, String referenceArticle, String descriptionCourte, String modele, int quantite, String descriptionLongue, double prix, String image, boolean superClient, boolean actif) {
		this.enseigne = enseigne;
		this.referenceArticle = referenceArticle;
		this.descriptionCourte = descriptionCourte;
		this.modele = modele;
		this.quantite = quantite;
		this.descriptionLongue = descriptionLongue;
		this.prix = prix;
		this.image = image;
		this.superClient = superClient;
		this.actif = actif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "enseigne", nullable = false, length = 50)
	@Enumerated(EnumType.STRING)
	public Enseigne getEnseigne() {
		return this.enseigne;
	}

	public void setEnseigne(Enseigne enseigne) {
		this.enseigne = enseigne;
	}

	@Column(name = "reference_article", nullable = false, length = 10)
	@NotNull
	@Length(min = 8, max = 8, message = "la référence doit faire exactement {max} caractères")
	public String getReferenceArticle() {
		return this.referenceArticle;
	}
	
	public void setReferenceArticle(String referenceArticle) {
		this.referenceArticle = referenceArticle;
	}

	@Column(name = "description_courte", nullable = false)
	@NotNull
	@Length(min = 2, max = 20, message = "la courte description doit être entre {min} et {max} caractères")
	public String getDescriptionCourte() {
		return this.descriptionCourte;
	}

	public void setDescriptionCourte(String descriptionCourte) {
		this.descriptionCourte = descriptionCourte;
	}

	@Column(name = "modele", nullable = false, length = 50)
	@NotNull
	@Length(min = 2, max = 20, message = "le modèle doit être entre {min} et {max} caractères")
	public String getModele() {
		return this.modele;
	}

	public void setModele(String modele) {
		this.modele = modele;
	}

	@Column(name = "quantite", nullable = false)
	@Range(min = 1, message = "La quantité doit être supérieure à {min} unités")
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@Column(name = "description_longue", nullable = false, length = 65535)
	@NotNull
	@Length(min = 2, message = "la longue description doit être supérieure à {min} caractères")
	public String getDescriptionLongue() {
		return this.descriptionLongue;
	}

	public void setDescriptionLongue(String descriptionLongue) {
		this.descriptionLongue = descriptionLongue;
	}

	@Column(name = "prix", nullable = false, precision = 22, scale = 0)
	public double getPrix() {
		return this.prix;
	}

	public void setPrix(double prix) {
		this.prix = prix;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "super_client", nullable = false)
	public boolean isSuperClient() {
		return this.superClient;
	}

	public void setSuperClient(boolean superClient) {
		this.superClient = superClient;
	}
	
	@Column(name = "actif", nullable = false)
	public boolean isActif() {
		return this.actif;
	}

	public void setActif(boolean actif) {
		this.actif = actif;
	}

}
