package fr.flst.mmargr.model;

// default package
// Generated 12 mai 2014 16:29:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

/**
 * CodePromo generated by hbm2java
 */
@Entity
@Table(name = "code_promo", catalog = "java")
public class CodePromo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5877643538268046486L;
	private String id;
	private Enseigne enseigne;
	private Date dateDebut;
	private Date dateFin;
	private TypePromotion typePromotion;
	private Integer pourcentage;
	private String reference;

	public CodePromo() {
	}

	public CodePromo(String id, Enseigne enseigne, Date dateDebut, Date dateFin, TypePromotion typePromotion) {
		this.id = id;
		this.enseigne = enseigne;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.typePromotion = typePromotion;
	}

	public CodePromo(String id, Enseigne enseigne, Date dateDebut, Date dateFin, TypePromotion typePromotion, Integer pourcentage, String reference) {
		this.id = id;
		this.enseigne = enseigne;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.typePromotion = typePromotion;
		this.pourcentage = pourcentage;
		this.reference = reference;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(min = 2, max = 5, message = "l'id doit faire être entre {min} et {max} caractères")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "enseigne", nullable = false, length = 50)
	@Enumerated(EnumType.STRING)
	public Enseigne getEnseigne() {
		return this.enseigne;
	}

	public void setEnseigne(Enseigne enseigne) {
		this.enseigne = enseigne;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin", nullable = false, length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "type_promotion", nullable = false, length = 50)
	@Enumerated(EnumType.STRING)
	public TypePromotion getTypePromotion() {
		return this.typePromotion;
	}

	public void setTypePromotion(TypePromotion typePromotion) {
		this.typePromotion = typePromotion;
	}

	@Column(name = "pourcentage")
	public Integer getPourcentage() {
		return this.pourcentage;
	}

	public void setPourcentage(Integer pourcentage) {
		this.pourcentage = pourcentage;
	}

	@Column(name = "reference", length = 10)
	@NotNull
	@Length(max = 10, message = "la référence doit faire au maximum {max} caractères")
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

}
