package fr.flst.mmargr.model;

// default package
// Generated 11 mai 2014 18:17:57 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Range;

/**
 * ModeLivraison generated by hbm2java
 */
@Entity
@Table(name = "mode_livraison", catalog = "java")
public class ModeLivraison implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4456886854378529953L;
	
	private Integer id;
	private String label;
	private double coutClassique;
	private double coutSuper;

	public ModeLivraison() {
	}

	public ModeLivraison(String label, double coutClassique, double coutSuper) {
		this.label = label;
		this.coutClassique = coutClassique;
		this.coutSuper = coutSuper;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "label", nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "cout_classique", nullable = false, precision = 22, scale = 0)
	@Range(max = 10)
	public double getCoutClassique() {
		return this.coutClassique;
	}

	public void setCoutClassique(double coutClassique) {
		this.coutClassique = coutClassique;
	}

	@Column(name = "cout_super", nullable = false, precision = 22, scale = 0)
	@Range(max = 10)
	public double getCoutSuper() {
		return this.coutSuper;
	}

	public void setCoutSuper(double coutSuper) {
		this.coutSuper = coutSuper;
	}

}
