package fr.flst.mmargr.model;

// default package
// Generated 12 mai 2014 20:34:02 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paiement generated by hbm2java
 */
@Entity
@Table(name = "paiement", catalog = "java")
public class Paiement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 437823123841899813L;
	private Integer id;
	private String label;
	private boolean clientClassique;
	private boolean superClient;

	public Paiement() {
	}

	public Paiement(String label, boolean clientClassique, boolean superClient) {
		this.label = label;
		this.clientClassique = clientClassique;
		this.superClient = superClient;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "label", nullable = false, length = 50)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "client_classique", nullable = false)
	public boolean isClientClassique() {
		return this.clientClassique;
	}

	public void setClientClassique(boolean clientClassique) {
		this.clientClassique = clientClassique;
	}

	@Column(name = "super_client", nullable = false)
	public boolean isSuperClient() {
		return this.superClient;
	}

	public void setSuperClient(boolean superClient) {
		this.superClient = superClient;
	}

}
