package fr.flst.mmargr.model;

// default package
// Generated 11 mai 2014 23:23:39 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.Range;

/**
 * Relai generated by hbm2java
 */
@Entity
@Table(name = "relai", catalog = "java")
public class Relai implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2204132701300677687L;
	private Integer id;
	private Adresse adresse;
	private int numeroRelai;
	private String label;
	private boolean actif = true;

	public Relai() {
	}

	public Relai(int numeroRelai, String label, boolean actif) {
		this.numeroRelai = numeroRelai;
		this.label = label;
		this.actif = actif;
	}

	public Relai(Adresse adresse, int numeroRelai, String label, boolean actif) {
		this.adresse = adresse;
		this.numeroRelai = numeroRelai;
		this.label = label;
		this.actif = actif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.ALL})
	@JoinColumn(name = "id_adresse")
	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	@Column(name = "numero_relai", nullable = false)
	@NotNull
	@Range(min = 9999, max = 100000, message = "le numero de relai doit faire exactement 5 chiffres")
	public int getNumeroRelai() {
		return this.numeroRelai;
	}

	public void setNumeroRelai(int numeroRelai) {
		this.numeroRelai = numeroRelai;
	}

	@Column(name = "label", nullable = false, length = 50)
	@NotNull
	@Length(min = 2, max = 50, message = "le nom du relai doit être compris entre {min} et {max} caractères")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "actif", nullable = false)
	public boolean isActif() {
		return this.actif;
	}

	public void setActif(boolean actif) {
		this.actif = actif;
	}

}
