// default package
// Generated 13 mai 2014 00:11:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "java")
public class Adresse implements java.io.Serializable {

	private Integer id;
	private String numeroRue;
	private String complement;
	private String codePostal;
	private String ville;
	private Set<User> users = new HashSet<User>(0);
	private Set<Relai> relais = new HashSet<Relai>(0);

	public Adresse() {
	}

	public Adresse(String numeroRue, String complement, String codePostal, String ville) {
		this.numeroRue = numeroRue;
		this.complement = complement;
		this.codePostal = codePostal;
		this.ville = ville;
	}

	public Adresse(String numeroRue, String complement, String codePostal, String ville, Set<User> users, Set<Relai> relais) {
		this.numeroRue = numeroRue;
		this.complement = complement;
		this.codePostal = codePostal;
		this.ville = ville;
		this.users = users;
		this.relais = relais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "numero_rue", nullable = false)
	public String getNumeroRue() {
		return this.numeroRue;
	}

	public void setNumeroRue(String numeroRue) {
		this.numeroRue = numeroRue;
	}

	@Column(name = "complement", nullable = false)
	public String getComplement() {
		return this.complement;
	}

	public void setComplement(String complement) {
		this.complement = complement;
	}

	@Column(name = "code_postal", nullable = false, length = 10)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "ville", nullable = false, length = 25)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Relai> getRelais() {
		return this.relais;
	}

	public void setRelais(Set<Relai> relais) {
		this.relais = relais;
	}

}
