// default package
// Generated 13 mai 2014 00:11:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article", catalog = "java")
public class Article implements java.io.Serializable {

	private Integer id;
	private String enseigne;
	private String referenceArticle;
	private String descriptionCourte;
	private String modele;
	private int quantite;
	private String descriptionLongue;
	private double prix;
	private String image;
	private boolean superClient;
	private boolean actif;
	private Set<LigneCommande> ligneCommandes = new HashSet<LigneCommande>(0);

	public Article() {
	}

	public Article(String enseigne, String referenceArticle, String descriptionCourte, String modele, int quantite, String descriptionLongue, double prix, String image, boolean superClient,
			boolean actif) {
		this.enseigne = enseigne;
		this.referenceArticle = referenceArticle;
		this.descriptionCourte = descriptionCourte;
		this.modele = modele;
		this.quantite = quantite;
		this.descriptionLongue = descriptionLongue;
		this.prix = prix;
		this.image = image;
		this.superClient = superClient;
		this.actif = actif;
	}

	public Article(String enseigne, String referenceArticle, String descriptionCourte, String modele, int quantite, String descriptionLongue, double prix, String image, boolean superClient,
			boolean actif, Set<LigneCommande> ligneCommandes) {
		this.enseigne = enseigne;
		this.referenceArticle = referenceArticle;
		this.descriptionCourte = descriptionCourte;
		this.modele = modele;
		this.quantite = quantite;
		this.descriptionLongue = descriptionLongue;
		this.prix = prix;
		this.image = image;
		this.superClient = superClient;
		this.actif = actif;
		this.ligneCommandes = ligneCommandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "enseigne", nullable = false, length = 50)
	public String getEnseigne() {
		return this.enseigne;
	}

	public void setEnseigne(String enseigne) {
		this.enseigne = enseigne;
	}

	@Column(name = "reference_article", nullable = false, length = 10)
	public String getReferenceArticle() {
		return this.referenceArticle;
	}

	public void setReferenceArticle(String referenceArticle) {
		this.referenceArticle = referenceArticle;
	}

	@Column(name = "description_courte", nullable = false)
	public String getDescriptionCourte() {
		return this.descriptionCourte;
	}

	public void setDescriptionCourte(String descriptionCourte) {
		this.descriptionCourte = descriptionCourte;
	}

	@Column(name = "modele", nullable = false, length = 50)
	public String getModele() {
		return this.modele;
	}

	public void setModele(String modele) {
		this.modele = modele;
	}

	@Column(name = "quantite", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@Column(name = "description_longue", nullable = false, length = 65535)
	public String getDescriptionLongue() {
		return this.descriptionLongue;
	}

	public void setDescriptionLongue(String descriptionLongue) {
		this.descriptionLongue = descriptionLongue;
	}

	@Column(name = "prix", nullable = false, precision = 22, scale = 0)
	public double getPrix() {
		return this.prix;
	}

	public void setPrix(double prix) {
		this.prix = prix;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "super_client", nullable = false)
	public boolean isSuperClient() {
		return this.superClient;
	}

	public void setSuperClient(boolean superClient) {
		this.superClient = superClient;
	}

	@Column(name = "actif", nullable = false)
	public boolean isActif() {
		return this.actif;
	}

	public void setActif(boolean actif) {
		this.actif = actif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "article")
	public Set<LigneCommande> getLigneCommandes() {
		return this.ligneCommandes;
	}

	public void setLigneCommandes(Set<LigneCommande> ligneCommandes) {
		this.ligneCommandes = ligneCommandes;
	}

}
