// default package
// Generated 12 mai 2014 16:29:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CodePromoId generated by hbm2java
 */
@Embeddable
public class CodePromoId implements java.io.Serializable {

	private String id;
	private String enseigne;
	private Date dateDebut;
	private Date dateFin;
	private String typePromotion;
	private Integer pourcentage;
	private String reference;

	public CodePromoId() {
	}

	public CodePromoId(String id, String enseigne, Date dateDebut, Date dateFin, String typePromotion) {
		this.id = id;
		this.enseigne = enseigne;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.typePromotion = typePromotion;
	}

	public CodePromoId(String id, String enseigne, Date dateDebut, Date dateFin, String typePromotion, Integer pourcentage, String reference) {
		this.id = id;
		this.enseigne = enseigne;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.typePromotion = typePromotion;
		this.pourcentage = pourcentage;
		this.reference = reference;
	}

	@Column(name = "id", unique = true, nullable = false, length = 5)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "enseigne", nullable = false, length = 50)
	public String getEnseigne() {
		return this.enseigne;
	}

	public void setEnseigne(String enseigne) {
		this.enseigne = enseigne;
	}

	@Column(name = "date_debut", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Column(name = "date_fin", nullable = false, length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "type_promotion", nullable = false, length = 50)
	public String getTypePromotion() {
		return this.typePromotion;
	}

	public void setTypePromotion(String typePromotion) {
		this.typePromotion = typePromotion;
	}

	@Column(name = "pourcentage")
	public Integer getPourcentage() {
		return this.pourcentage;
	}

	public void setPourcentage(Integer pourcentage) {
		this.pourcentage = pourcentage;
	}

	@Column(name = "reference", length = 10)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CodePromoId))
			return false;
		CodePromoId castOther = (CodePromoId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getEnseigne() == castOther.getEnseigne()) || (this.getEnseigne() != null && castOther.getEnseigne() != null && this.getEnseigne().equals(castOther.getEnseigne())))
				&& ((this.getDateDebut() == castOther.getDateDebut()) || (this.getDateDebut() != null && castOther.getDateDebut() != null && this.getDateDebut().equals(castOther.getDateDebut())))
				&& ((this.getDateFin() == castOther.getDateFin()) || (this.getDateFin() != null && castOther.getDateFin() != null && this.getDateFin().equals(castOther.getDateFin())))
				&& ((this.getTypePromotion() == castOther.getTypePromotion()) || (this.getTypePromotion() != null && castOther.getTypePromotion() != null && this.getTypePromotion().equals(
						castOther.getTypePromotion())))
				&& ((this.getPourcentage() == castOther.getPourcentage()) || (this.getPourcentage() != null && castOther.getPourcentage() != null && this.getPourcentage().equals(
						castOther.getPourcentage())))
				&& ((this.getReference() == castOther.getReference()) || (this.getReference() != null && castOther.getReference() != null && this.getReference().equals(castOther.getReference())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getEnseigne() == null ? 0 : this.getEnseigne().hashCode());
		result = 37 * result + (getDateDebut() == null ? 0 : this.getDateDebut().hashCode());
		result = 37 * result + (getDateFin() == null ? 0 : this.getDateFin().hashCode());
		result = 37 * result + (getTypePromotion() == null ? 0 : this.getTypePromotion().hashCode());
		result = 37 * result + (getPourcentage() == null ? 0 : this.getPourcentage().hashCode());
		result = 37 * result + (getReference() == null ? 0 : this.getReference().hashCode());
		return result;
	}

}
