// default package
// Generated 13 mai 2014 00:11:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Relai generated by hbm2java
 */
@Entity
@Table(name = "relai", catalog = "java")
public class Relai implements java.io.Serializable {

	private Integer id;
	private Adresse adresse;
	private int numeroRelai;
	private String label;
	private boolean actif;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Relai() {
	}

	public Relai(int numeroRelai, String label, boolean actif) {
		this.numeroRelai = numeroRelai;
		this.label = label;
		this.actif = actif;
	}

	public Relai(Adresse adresse, int numeroRelai, String label, boolean actif, Set<Commande> commandes) {
		this.adresse = adresse;
		this.numeroRelai = numeroRelai;
		this.label = label;
		this.actif = actif;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_adresse")
	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	@Column(name = "numero_relai", nullable = false)
	public int getNumeroRelai() {
		return this.numeroRelai;
	}

	public void setNumeroRelai(int numeroRelai) {
		this.numeroRelai = numeroRelai;
	}

	@Column(name = "label", nullable = false, length = 50)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "actif", nullable = false)
	public boolean isActif() {
		return this.actif;
	}

	public void setActif(boolean actif) {
		this.actif = actif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relai")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
